
cache table ga_click_event as
select distinct case when a.ec='首页' then 'click' else 'event' end type,
a.uid dim16,
cd14 pid,
case when a.ec='01' then b.a when a.ec='首页' then regexp_extract(a.el,'_([^_]+)_([^_]+)',2) else b.cd4 end article_id
from bi_ods_ga.ods_app_sdk_log_orc a
lateral view json_tuple(a.ecp,'a','c','tv','p','sp','atp','20','4','21','13','14') b as a,c,tv,p,sp,atp,cd20,cd4,cd21,cd13,cd14
where a.dt='2020-09-20' and a.it between '2020-09-20' and concat('2020-09-20',' 23:59:59') and a.uid<>'' and a.uid<>'0'
and (a.ec='首页' and a.ea='首页站内文章点击' and a.el regexp '^推荐_'
or a.ec='增强型电子商务' and a.ea='添加到购物车' and b.cd21 regexp '^首页_推荐_feed流_');


--曝光
cache table temp_exposure as
select distinct
md5(concat(user_id,nvl(type,''),nvl(pid,''),nvl(article_id,''),nvl(remark4,''))) id,
creation_date,
user_id,
device_id,
type,
remark3,
version,
article_id,
remark4,
pid
from(
select row_number()over(partition by a.uid,b.a,b.pid order by a.it) r,
a.it creation_date,
a.uid user_id,
case when a.imei<>'' then a.imei else a.did end device_id,
b.tv type,
b.p remark3,
a.av version,
b.a article_id,
b.c remark4,
b.pid
from bi_ods_ga.ods_app_sdk_log a
lateral view json_tuple(a.ecp,'a','c','tv','p','sp','pid') b as a,c,tv,p,sp,pid
where a.dt='2020-09-20' and a.ec='01' and a.ea='01' and b.sp='0' and a.it between '2020-09-20' and concat('2020-09-20',' 23:59:59') and a.uid<>'' and a.uid<>'0' and b.c in('1','2','5','6','8','11','31','66')) a
where r=1;


--曝光关联
cache table temp_click_event as
select a.id,
if(b.dim16 is null,'0','1') is_click,
if(c.dim16 is null,'0','1') is_event
from temp_exposure a
left join (select dim16,article_id,pid from ga_click_event where type='click') b on a.user_id=b.dim16 and a.article_id=b.article_id and a.pid=b.pid
left join (select dim16,article_id,pid from ga_click_event where type='event') c on a.user_id=c.dim16 and a.article_id=c.article_id and a.pid=c.pid;

create table bi_test.zyl_tmp_200928_1 as
select a.id,
a.creation_date,
a.user_id,
a.device_id,
'' remark,
a.type,
'' remark2,
a.remark3,
a.version,
a.article_id,
a.remark4,
b.is_click,
b.is_event,
'2020-09-20' dt
from temp_exposure a
left join temp_click_event b on a.id=b.id;



cache table tmp as
select id,user_id,if(u_article_orders>0,1,0) is_order
from(
select id,
user_id,
sum(orders)over(partition by user_id,article_id order by creation_date range between current row and 259200 FOLLOWING) u_article_orders
from(
select a.id,unix_timestamp(a.creation_date) creation_date,a.user_id,a.article_id,0 orders
from bi_test.zyl_tmp_200928_1 a
union all
select 'smzdm' id,unix_timestamp(a.order_time) creation_date,substr(a.smzdm_id,1,10) suserid,a.article_id,nvl(a.sales,0) orders
from dwa.dwa_gmv_order a
where a.dt>='2020-09' and a.smzdm_id>'0' and a.article_id>'0' and a.status=1 and a.flag=1) a) a
where id<>'smzdm';


create table bi_test.zyl_tmp_200928_2 as
select a.id,
a.creation_date,
a.user_id,
a.device_id,
a.remark,
a.type,
a.remark2,
a.remark3,
a.version,
a.article_id,
a.remark4,
a.is_click,
a.is_event,
b.is_order,
a.dt
from bi_test.zyl_tmp_200928_1 a
left join tmp b on a.id=b.id;


create table bi_test.zyl_tmp_200928_3 as
select md5(concat(a.user_id,nvl(a.ab_test,''),nvl(a.pid,''),nvl(b.article_hash_id,a.article_id),nvl(a.channel_id,''))) id,
nvl(b.article_hash_id,a.article_id) a_id,
a.ab_test,
a.pid,
a.user_id,
a.article_id,
a.channel_id,
a.log_time,
a.featuremap
from bi_log.feature_log_extract a
left join (select article_id,article_hash_id from stg.db_smzdm_article_article_index where dt='2020-09-27') b on a.article_id=b.article_id and a.channel_id in(11,6,8,31,66)
where a.dt='2020-09-20' and a.featuremap is not null;

CREATE TABLE `bi_test.zyl_tmp_200928_4`(
  id string,
ab_test string,
pid string,
user_id string,
article_id string,
adcode string,
age_bin string,
age1_p string,
age2_p string,
age3_p string,
age4_p string,
age5_p string,
area string,
article_image_count string,
article_tag string,
article_type string,
article_word_count string,
author_attr string,
b_cnt_article_1d string,
b_cnt_article_30d string,
b_cnt_article_7d string,
b_mean_ctr_1d string,
b_mean_ctr_30d string,
b_mean_ctr_7d string,
b_mean_sec_1d string,
b_mean_sec_30d string,
b_mean_sec_7d string,
baike_com string,
baike_gmv string,
baike_orders string,
baikeid string,
baoliao string,
baoliao_source_type string,
baoliao_userid string,
brandid string,
buzhi string,
cate_decision_cost string,
cate_people_group string,
cate_repurchase_period string,
cate_season string,
cate_sex string,
cate_warranty_period string,
cate1_ordertime_creation_date string,
cate2_ordertime_creation_date string,
cate3_ordertime_creation_date string,
cate4_ordertime_creation_date string,
category_top_n string,
channel_pref string,
channelid string,
chaojiyouxuan string,
city string,
click_home string,
click_home_per_min string,
com string,
comment string,
country string,
coupon string,
ctr_home string,
ctr_lat string,
ctr_lng string,
dashang_people_count string,
device_typeid string,
district string,
event string,
faxian_caiyong_status string,
gc_type string,
geohashid string,
gmv string,
history_jingxuan_count string,
history_pub_count string,
imp_home string,
imp_home_per_min string,
impression_regist_time string,
impressions_interval string,
insert_card_count string,
is_30day_min_price string,
is_30day_min_price_exist_list string,
is_baopin string,
is_category_top_n_exist_list string,
is_jiajing string,
is_series string,
jifen string,
jinbi string,
jingyan string,
level string,
level1 string,
level2 string,
level3 string,
level4 string,
link_click_ratio string,
lk string,
lt_30day_avg_price_ratio string,
lt_30day_avg_price_ratio_exist_list string,
lt_last_price_ratio string,
lt_last_price_ratio_exist_list string,
mall_pref string,
mallid string,
orders string,
percent_reduction string,
pinglun string,
poi_typeid string,
pre_sale_start_time_creation_date string,
price string,
price_diff string,
price_last string,
product_ordertime_creation_date string,
province string,
pv_every_min string,
qiandao string,
reduce_price_type1 string,
reduce_price_type2 string,
reduce_price_type3 string,
reduce_price_type4 string,
reduce_price_type5 string,
reduce_price_type6 string,
reduce_price_type7 string,
reduce_price_type8 string,
score_article string,
score_quality string,
sec_click_every_min string,
sex_p string,
sexPREFratio_1 string,
sexPREFratio_2 string,
sexPREFratio_3 string,
shoucang string,
single string,
subtitle_len string,
sv string,
title_len string,
title_population_type string,
title_sex string,
u_brand_ctr_1d string,
u_brand_ctr_30d string,
u_brand_ctr_7d string,
u_brand_sec_1d string,
u_brand_sec_30d string,
u_brand_sec_7d string,
u_cate_sex_1 string,
u_cate_sex_2 string,
u_cate_sex_3 string,
u_ctr_1d string,
u_ctr_30d string,
u_ctr_7d string,
u_sec_1d string,
u_sec_30d string,
u_sec_7d string,
ugz_author_time_diff string,
ugz_brand_time_diff string,
ugz_cate1_time_diff string,
ugz_cate2_time_diff string,
ugz_cate3_time_diff string,
ugz_cate4_time_diff string,
ugz_mall_time_diff string,
ugz_product_time_diff string,
ui_is_cargo string,
up_brand string,
up_level1 string,
up_level2 string,
up_level3 string,
up_level4 string,
up_tag_avg string,
up_tag_count string,
up_tag_max string,
up_tag_sum string,
urhoclick_brand_5m string,
urhoclick_cate1_5m string,
urhoclick_cate2_5m string,
urhoclick_cate3_5m string,
urhoclick_cate4_5m string,
urhoctr_brand_5m string,
urhoctr_cate1_5m string,
urhoctr_cate2_5m string,
urhoctr_cate3_5m string,
urhoctr_cate4_5m string,
urhoimp_brand_5m string,
urhoimp_cate1_5m string,
urhoimp_cate2_5m string,
urhoimp_cate3_5m string,
urhoimp_cate4_5m string,
url_com string,
url_gmv string,
url_orders string,
user_com string,
user_gmv string,
user_orders string,
week_day string,
yh_type string,
yuanchuang string,
zhi string,
zhi_buzhi string,
zhi_jia_buzhi string,
zhi_percent_pinglun string,
zip string,
age string,
province_code string,
sex string,
zhimafen string,
l1_atcgrd string,
l1_pp_delta string,
l1_upp string,
l2_atcgrd string,
l2_pp_delta string,
l2_upp string,
l3_atcgrd string,
l3_pp_delta string,
l3_upp string,
l4_atcgrd string,
l4_pp_delta string,
l4_upp string,
urhoimp_cate1_24h string,
urhoimp_cate2_24h string,
urhoimp_cate3_24h string,
urhoimp_cate4_24h string,
urhoclick_cate1_24h string,
urhoclick_cate2_24h string,
urhoclick_cate3_24h string,
urhoclick_cate4_24h string,
urhoctr_cate1_24h string,
urhoctr_cate2_24h string,
urhoctr_cate3_24h string,
urhoctr_cate4_24h string,
urhoimp_brand_24h string,
urhoclick_brand_24h string,
urhoctr_brand_24h string,
urhoimp_cate1_15m string,
urhoimp_cate2_15m string,
urhoimp_cate3_15m string,
urhoimp_cate4_15m string,
urhoclick_cate1_15m string,
urhoclick_cate2_15m string,
urhoclick_cate3_15m string,
urhoclick_cate4_15m string,
urhoctr_cate1_15m string,
urhoctr_cate2_15m string,
urhoctr_cate3_15m string,
urhoctr_cate4_15m string,
urhoimp_brand_15m string,
urhoclick_brand_15m string,
urhoctr_brand_15m string,
urhoimp_cate1_150s string,
urhoimp_cate2_150s string,
urhoimp_cate3_150s string,
urhoimp_cate4_150s string,
urhoclick_cate1_150s string,
urhoclick_cate2_150s string,
urhoclick_cate3_150s string,
urhoclick_cate4_150s string,
urhoctr_cate1_150s string,
urhoctr_cate2_150s string,
urhoctr_cate3_150s string,
urhoctr_cate4_150s string,
urhoimp_brand_150s string,
urhoclick_brand_150s string,
urhoctr_brand_150s string,
urseclick_cate1_15m string,
urseclick_cate2_15m string,
urseclick_cate3_15m string,
urseclick_cate4_15m string,
urseclick_brand_15m string,
urseclick_cate1_24h string,
urseclick_cate2_24h string,
urseclick_cate3_24h string,
urseclick_cate4_24h string,
urseclick_brand_24h string,
ulastclick_cate1 string,
ulastclick_cate2 string,
ulastclick_cate3 string,
ulastclick_cate4 string,
mall_last_1h_ec string,
mall_last_1h_ec_trend string,
mall_last_1h_imp string,
mall_last_1h_imp_trend string,
mall_last_1h_ec_per_imp string,
mall_last_1h_ec_per_imp_trend string,
mall_cate_last_1h_ec string,
mall_cate_last_1h_ec_trend string,
mall_cate_last_1h_imp string,
mall_cate_last_1h_imp_trend string,
mall_cate_last_1h_ec_per_imp string,
mall_cate_last_1h_ec_per_imp_trend string,
u_last_clk_cate1 string,
u_last_clk_cate1_is_same string,
u_last_clk_cate2 string,
u_last_clk_cate2_is_same string,
u_last_clk_cate3 string,
u_last_clk_cate3_is_same string,
u_last_clk_cate4 string,
u_last_clk_cate4_is_same string,
u_last_clk_brand string,
u_last_clk_brand_is_same string,
u_last_clk_mall string,
u_last_clk_mall_is_same string,
u_last_clk_cate1_delta string,
u_last_clk_cate2_delta string,
u_last_clk_cate3_delta string,
u_last_clk_cate4_delta string,
u_last_clk_brand_delta string,
u_last_clk_mall_delta string,
single_imp_ec string,
avg_time string,
avg_finish string,
mu_o_1d string,
mu_o_7d string,
mu_o_30d string,
mu_g_1d string,
mu_g_7d string,
mu_g_30d string,
mu_sec_1d string,
mu_sec_7d string,
mu_sec_30d string,
mu_op_1d string,
mu_op_7d string,
mu_op_30d string,
mu_o_3h_rt string,
mu_g_3h_rt string,
mu_sec_3h_rt string,
mu_op_3h_rt string,
uo_l1_1d_o string,
uo_l1_7d_o string,
uo_l1_30d_o string,
uo_l1_1d_g string,
uo_l1_7d_g string,
uo_l1_30d_g string,
uo_l2_1d_o string,
uo_l2_7d_o string,
uo_l2_30d_o string,
uo_l2_1d_g string,
uo_l2_7d_g string,
uo_l2_30d_g string,
uo_l3_1d_o string,
uo_l3_7d_o string,
uo_l3_30d_o string,
uo_l3_1d_g string,
uo_l3_7d_g string,
uo_l3_30d_g string,
uo_l4_1d_o string,
uo_l4_7d_o string,
uo_l4_30d_o string,
uo_l4_1d_g string,
uo_l4_7d_g string,
uo_l4_30d_g string,
uo_l1_1d_sec string,
uo_l1_7d_sec string,
uo_l1_30d_sec string,
uo_l2_1d_sec string,
uo_l2_7d_sec string,
uo_l2_30d_sec string,
uo_l3_1d_sec string,
uo_l3_7d_sec string,
uo_l3_30d_sec string,
uo_l4_1d_sec string,
uo_l4_7d_sec string,
uo_l4_30d_sec string,
uo_l1_1d_op string,
uo_l1_7d_op string,
uo_l1_30d_op string,
uo_l2_1d_op string,
uo_l2_7d_op string,
uo_l2_30d_op string,
uo_l3_1d_op string,
uo_l3_7d_op string,
uo_l3_30d_op string,
uo_l4_1d_op string,
uo_l4_7d_op string,
uo_l4_30d_op string,
uo_l1_3h_g_rt string,
uo_l1_3h_o_rt string,
uo_l2_3h_g_rt string,
uo_l2_3h_o_rt string,
uo_l3_3h_g_rt string,
uo_l3_3h_o_rt string,
uo_l4_3h_g_rt string,
uo_l4_3h_o_rt string,
uo_l1_3h_sec_rt string,
uo_l2_3h_sec_rt string,
uo_l3_3h_sec_rt string,
uo_l4_3h_sec_rt string,
uo_l1_3h_op_rt string,
uo_l2_3h_op_rt string,
uo_l3_3h_op_rt string,
uo_l4_3h_op_rt string,
os_version string,
screen_height string,
screen_width string,
app_market string,
net_type string,
mu_o_12h_rt string,
mu_sec_12h_rt string,
mu_op_12h_rt string,
uo_l1_90d_o string,
uo_l1_180d_o string,
uo_l2_90d_o string,
uo_l2_180d_o string,
uo_l3_90d_o string,
uo_l3_180d_o string,
uo_l4_90d_o string,
uo_l4_180d_o string,
uo_l1_90d_sec string,
uo_l1_180d_sec string,
uo_l2_90d_sec string,
uo_l2_180d_sec string,
uo_l3_90d_sec string,
uo_l3_180d_sec string,
uo_l4_90d_sec string,
uo_l4_180d_sec string,
uo_l1_90d_op string,
uo_l1_180d_op string,
uo_l2_90d_op string,
uo_l2_180d_op string,
uo_l3_90d_op string,
uo_l3_180d_op string,
uo_l4_90d_op string,
uo_l4_180d_op string,
anticheat_by_zhi string,
anticheat_by_comment string,
anticheat_by_shoucang string,
up_level1_ct_3d string,
up_level1_ct_7d string,
up_level1_ct_30d string,
up_level1_ct_90d string,
up_level1_ct_180d string,
up_level2_ct_3d string,
up_level2_ct_7d string,
up_level2_ct_30d string,
up_level2_ct_90d string,
up_level2_ct_180d string,
up_level3_ct_3d string,
up_level3_ct_7d string,
up_level3_ct_30d string,
up_level3_ct_90d string,
up_level3_ct_180d string,
up_level4_ct_3d string,
up_level4_ct_7d string,
up_level4_ct_30d string,
up_level4_ct_90d string,
up_level4_ct_180d string,
up_level1_sec_3d string,
up_level1_sec_7d string,
up_level1_sec_30d string,
up_level1_sec_90d string,
up_level1_sec_180d string,
up_level2_sec_3d string,
up_level2_sec_7d string,
up_level2_sec_30d string,
up_level2_sec_90d string,
up_level2_sec_180d string,
up_level3_sec_3d string,
up_level3_sec_7d string,
up_level3_sec_30d string,
up_level3_sec_90d string,
up_level3_sec_180d string,
up_level4_sec_3d string,
up_level4_sec_7d string,
up_level4_sec_30d string,
up_level4_sec_90d string,
up_level4_sec_180d string,
ua_clst_3h_ctr string,
ua_clst_3h_sec string,
u_clst_id string,
is_jingdou string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat';

drop table ga_click_event;
drop table temp_exposure;
drop table temp_click_event;
drop table tmp;



insert overwrite table bi_test.zyl_tmp_200928_4
select a.id,
a.ab_test,
a.pid,
a.user_id,
a.article_id,
b.adcode,
b.age_bin,
b.age1_p,
b.age2_p,
b.age3_p,
b.age4_p,
b.age5_p,
b.area,
b.article_image_count,
b.article_tag,
b.article_type,
b.article_word_count,
b.author_attr,
b.b_cnt_article_1d,
b.b_cnt_article_30d,
b.b_cnt_article_7d,
b.b_mean_ctr_1d,
b.b_mean_ctr_30d,
b.b_mean_ctr_7d,
b.b_mean_sec_1d,
b.b_mean_sec_30d,
b.b_mean_sec_7d,
b.baike_com,
b.baike_gmv,
b.baike_orders,
b.baikeid,
b.baoliao,
b.baoliao_source_type,
b.baoliao_userid,
b.brandid,
b.buzhi,
b.cate_decision_cost,
b.cate_people_group,
b.cate_repurchase_period,
b.cate_season,
b.cate_sex,
b.cate_warranty_period,
b.cate1_ordertime_creation_date,
b.cate2_ordertime_creation_date,
b.cate3_ordertime_creation_date,
b.cate4_ordertime_creation_date,
b.category_top_n,
b.channel_pref,
b.channelid,
b.chaojiyouxuan,
b.city,
b.click_home,
b.click_home_per_min,
b.com,
b.comment,
b.country,
b.coupon,
b.ctr_home,
b.ctr_lat,
b.ctr_lng,
b.dashang_people_count,
b.device_typeid,
b.district,
b.event,
b.faxian_caiyong_status,
b.gc_type,
b.geohashid,
b.gmv,
b.history_jingxuan_count,
b.history_pub_count,
b.imp_home,
b.imp_home_per_min,
b.impression_regist_time,
b.impressions_interval,
b.insert_card_count,
b.is_30day_min_price,
b.is_30day_min_price_exist_list,
b.is_baopin,
b.is_category_top_n_exist_list,
b.is_jiajing,
b.is_series,
b.jifen,
b.jinbi,
b.jingyan,
b.level,
b.level1,
b.level2,
b.level3,
b.level4,
b.link_click_ratio,
b.lk,
b.lt_30day_avg_price_ratio,
b.lt_30day_avg_price_ratio_exist_list,
b.lt_last_price_ratio,
b.lt_last_price_ratio_exist_list,
b.mall_pref,
b.mallid,
b.orders,
b.percent_reduction,
b.pinglun,
b.poi_typeid,
b.pre_sale_start_time_creation_date,
b.price,
b.price_diff,
b.price_last,
b.product_ordertime_creation_date,
b.province,
b.pv_every_min,
b.qiandao,
b.reduce_price_type1,
b.reduce_price_type2,
b.reduce_price_type3,
b.reduce_price_type4,
b.reduce_price_type5,
b.reduce_price_type6,
b.reduce_price_type7,
b.reduce_price_type8,
b.score_article,
b.score_quality,
b.sec_click_every_min,
b.sex_p,
b.sexPREFratio_1,
b.sexPREFratio_2,
b.sexPREFratio_3,
b.shoucang,
b.single,
b.subtitle_len,
b.sv,
b.title_len,
b.title_population_type,
b.title_sex,
b.u_brand_ctr_1d,
b.u_brand_ctr_30d,
b.u_brand_ctr_7d,
b.u_brand_sec_1d,
b.u_brand_sec_30d,
b.u_brand_sec_7d,
b.u_cate_sex_1,
b.u_cate_sex_2,
b.u_cate_sex_3,
b.u_ctr_1d,
b.u_ctr_30d,
b.u_ctr_7d,
b.u_sec_1d,
b.u_sec_30d,
b.u_sec_7d,
b.ugz_author_time_diff,
b.ugz_brand_time_diff,
b.ugz_cate1_time_diff,
b.ugz_cate2_time_diff,
b.ugz_cate3_time_diff,
b.ugz_cate4_time_diff,
b.ugz_mall_time_diff,
b.ugz_product_time_diff,
b.ui_is_cargo,
b.up_brand,
b.up_level1,
b.up_level2,
b.up_level3,
b.up_level4,
b.up_tag_avg,
b.up_tag_count,
b.up_tag_max,
b.up_tag_sum,
b.urhoclick_brand_5m,
b.urhoclick_cate1_5m,
b.urhoclick_cate2_5m,
b.urhoclick_cate3_5m,
b.urhoclick_cate4_5m,
b.urhoctr_brand_5m,
b.urhoctr_cate1_5m,
b.urhoctr_cate2_5m,
b.urhoctr_cate3_5m,
b.urhoctr_cate4_5m,
b.urhoimp_brand_5m,
b.urhoimp_cate1_5m,
b.urhoimp_cate2_5m,
b.urhoimp_cate3_5m,
b.urhoimp_cate4_5m,
b.url_com,
b.url_gmv,
b.url_orders,
b.user_com,
b.user_gmv,
b.user_orders,
b.week_day,
b.yh_type,
b.yuanchuang,
b.zhi,
b.zhi_buzhi,
b.zhi_jia_buzhi,
b.zhi_percent_pinglun,
b.zip,
b.age,
b.province_code,
b.sex,
b.zhimafen,
b.l1_atcgrd,
b.l1_pp_delta,
b.l1_upp,
b.l2_atcgrd,
b.l2_pp_delta,
b.l2_upp,
b.l3_atcgrd,
b.l3_pp_delta,
b.l3_upp,
b.l4_atcgrd,
b.l4_pp_delta,
b.l4_upp,
b.urhoimp_cate1_24h,
b.urhoimp_cate2_24h,
b.urhoimp_cate3_24h,
b.urhoimp_cate4_24h,
b.urhoclick_cate1_24h,
b.urhoclick_cate2_24h,
b.urhoclick_cate3_24h,
b.urhoclick_cate4_24h,
b.urhoctr_cate1_24h,
b.urhoctr_cate2_24h,
b.urhoctr_cate3_24h,
b.urhoctr_cate4_24h,
b.urhoimp_brand_24h,
b.urhoclick_brand_24h,
b.urhoctr_brand_24h,
b.urhoimp_cate1_15m,
b.urhoimp_cate2_15m,
b.urhoimp_cate3_15m,
b.urhoimp_cate4_15m,
b.urhoclick_cate1_15m,
b.urhoclick_cate2_15m,
b.urhoclick_cate3_15m,
b.urhoclick_cate4_15m,
b.urhoctr_cate1_15m,
b.urhoctr_cate2_15m,
b.urhoctr_cate3_15m,
b.urhoctr_cate4_15m,
b.urhoimp_brand_15m,
b.urhoclick_brand_15m,
b.urhoctr_brand_15m,
b.urhoimp_cate1_150s,
b.urhoimp_cate2_150s,
b.urhoimp_cate3_150s,
b.urhoimp_cate4_150s,
b.urhoclick_cate1_150s,
b.urhoclick_cate2_150s,
b.urhoclick_cate3_150s,
b.urhoclick_cate4_150s,
b.urhoctr_cate1_150s,
b.urhoctr_cate2_150s,
b.urhoctr_cate3_150s,
b.urhoctr_cate4_150s,
b.urhoimp_brand_150s,
b.urhoclick_brand_150s,
b.urhoctr_brand_150s,
b.urseclick_cate1_15m,
b.urseclick_cate2_15m,
b.urseclick_cate3_15m,
b.urseclick_cate4_15m,
b.urseclick_brand_15m,
b.urseclick_cate1_24h,
b.urseclick_cate2_24h,
b.urseclick_cate3_24h,
b.urseclick_cate4_24h,
b.urseclick_brand_24h,
b.ulastclick_cate1,
b.ulastclick_cate2,
b.ulastclick_cate3,
b.ulastclick_cate4,
b.mall_last_1h_ec,
b.mall_last_1h_ec_trend,
b.mall_last_1h_imp,
b.mall_last_1h_imp_trend,
b.mall_last_1h_ec_per_imp,
b.mall_last_1h_ec_per_imp_trend,
b.mall_cate_last_1h_ec,
b.mall_cate_last_1h_ec_trend,
b.mall_cate_last_1h_imp,
b.mall_cate_last_1h_imp_trend,
b.mall_cate_last_1h_ec_per_imp,
b.mall_cate_last_1h_ec_per_imp_trend,
b.u_last_clk_cate1,
b.u_last_clk_cate1_is_same,
b.u_last_clk_cate2,
b.u_last_clk_cate2_is_same,
b.u_last_clk_cate3,
b.u_last_clk_cate3_is_same,
b.u_last_clk_cate4,
b.u_last_clk_cate4_is_same,
b.u_last_clk_brand,
b.u_last_clk_brand_is_same,
b.u_last_clk_mall,
b.u_last_clk_mall_is_same,
b.u_last_clk_cate1_delta,
b.u_last_clk_cate2_delta,
b.u_last_clk_cate3_delta,
b.u_last_clk_cate4_delta,
b.u_last_clk_brand_delta,
b.u_last_clk_mall_delta,
b.single_imp_ec,
b.avg_time,
b.avg_finish,
b.mu_o_1d,
b.mu_o_7d,
b.mu_o_30d,
b.mu_g_1d,
b.mu_g_7d,
b.mu_g_30d,
b.mu_sec_1d,
b.mu_sec_7d,
b.mu_sec_30d,
b.mu_op_1d,
b.mu_op_7d,
b.mu_op_30d,
b.mu_o_3h_rt,
b.mu_g_3h_rt,
b.mu_sec_3h_rt,
b.mu_op_3h_rt,
b.uo_l1_1d_o,
b.uo_l1_7d_o,
b.uo_l1_30d_o,
b.uo_l1_1d_g,
b.uo_l1_7d_g,
b.uo_l1_30d_g,
b.uo_l2_1d_o,
b.uo_l2_7d_o,
b.uo_l2_30d_o,
b.uo_l2_1d_g,
b.uo_l2_7d_g,
b.uo_l2_30d_g,
b.uo_l3_1d_o,
b.uo_l3_7d_o,
b.uo_l3_30d_o,
b.uo_l3_1d_g,
b.uo_l3_7d_g,
b.uo_l3_30d_g,
b.uo_l4_1d_o,
b.uo_l4_7d_o,
b.uo_l4_30d_o,
b.uo_l4_1d_g,
b.uo_l4_7d_g,
b.uo_l4_30d_g,
b.uo_l1_1d_sec,
b.uo_l1_7d_sec,
b.uo_l1_30d_sec,
b.uo_l2_1d_sec,
b.uo_l2_7d_sec,
b.uo_l2_30d_sec,
b.uo_l3_1d_sec,
b.uo_l3_7d_sec,
b.uo_l3_30d_sec,
b.uo_l4_1d_sec,
b.uo_l4_7d_sec,
b.uo_l4_30d_sec,
b.uo_l1_1d_op,
b.uo_l1_7d_op,
b.uo_l1_30d_op,
b.uo_l2_1d_op,
b.uo_l2_7d_op,
b.uo_l2_30d_op,
b.uo_l3_1d_op,
b.uo_l3_7d_op,
b.uo_l3_30d_op,
b.uo_l4_1d_op,
b.uo_l4_7d_op,
b.uo_l4_30d_op,
b.uo_l1_3h_g_rt,
b.uo_l1_3h_o_rt,
b.uo_l2_3h_g_rt,
b.uo_l2_3h_o_rt,
b.uo_l3_3h_g_rt,
b.uo_l3_3h_o_rt,
b.uo_l4_3h_g_rt,
b.uo_l4_3h_o_rt,
b.uo_l1_3h_sec_rt,
b.uo_l2_3h_sec_rt,
b.uo_l3_3h_sec_rt,
b.uo_l4_3h_sec_rt,
b.uo_l1_3h_op_rt,
b.uo_l2_3h_op_rt,
b.uo_l3_3h_op_rt,
b.uo_l4_3h_op_rt,
b.os_version,
b.screen_height,
b.screen_width,
b.app_market,
b.net_type,
b.mu_o_12h_rt,
b.mu_sec_12h_rt,
b.mu_op_12h_rt,
b.uo_l1_90d_o,
b.uo_l1_180d_o,
b.uo_l2_90d_o,
b.uo_l2_180d_o,
b.uo_l3_90d_o,
b.uo_l3_180d_o,
b.uo_l4_90d_o,
b.uo_l4_180d_o,
b.uo_l1_90d_sec,
b.uo_l1_180d_sec,
b.uo_l2_90d_sec,
b.uo_l2_180d_sec,
b.uo_l3_90d_sec,
b.uo_l3_180d_sec,
b.uo_l4_90d_sec,
b.uo_l4_180d_sec,
b.uo_l1_90d_op,
b.uo_l1_180d_op,
b.uo_l2_90d_op,
b.uo_l2_180d_op,
b.uo_l3_90d_op,
b.uo_l3_180d_op,
b.uo_l4_90d_op,
b.uo_l4_180d_op,
b.anticheat_by_zhi,
b.anticheat_by_comment,
b.anticheat_by_shoucang,
b.up_level1_ct_3d,
b.up_level1_ct_7d,
b.up_level1_ct_30d,
b.up_level1_ct_90d,
b.up_level1_ct_180d,
b.up_level2_ct_3d,
b.up_level2_ct_7d,
b.up_level2_ct_30d,
b.up_level2_ct_90d,
b.up_level2_ct_180d,
b.up_level3_ct_3d,
b.up_level3_ct_7d,
b.up_level3_ct_30d,
b.up_level3_ct_90d,
b.up_level3_ct_180d,
b.up_level4_ct_3d,
b.up_level4_ct_7d,
b.up_level4_ct_30d,
b.up_level4_ct_90d,
b.up_level4_ct_180d,
b.up_level1_sec_3d,
b.up_level1_sec_7d,
b.up_level1_sec_30d,
b.up_level1_sec_90d,
b.up_level1_sec_180d,
b.up_level2_sec_3d,
b.up_level2_sec_7d,
b.up_level2_sec_30d,
b.up_level2_sec_90d,
b.up_level2_sec_180d,
b.up_level3_sec_3d,
b.up_level3_sec_7d,
b.up_level3_sec_30d,
b.up_level3_sec_90d,
b.up_level3_sec_180d,
b.up_level4_sec_3d,
b.up_level4_sec_7d,
b.up_level4_sec_30d,
b.up_level4_sec_90d,
b.up_level4_sec_180d,
b.ua_clst_3h_ctr,
b.ua_clst_3h_sec,
b.u_clst_id,
b.is_jingdou
from (select a.id,a.ab_test,a.pid,a.user_id,a.article_id,a.channel_id,a.featuremap
from(
select a.id,
a.ab_test,
a.pid,
a.user_id,
a.article_id,
a.channel_id,
a.featuremap,
row_number()over(partition by a.id order by a.log_time) r
from
--bi_test.zyl_tmp_200928_3
(select md5(concat(a.user_id,nvl(a.ab_test,''),nvl(a.pid,''),nvl(b.article_hash_id,a.article_id),nvl(a.channel_id,''))) id,
nvl(b.article_hash_id,a.article_id) a_id,
a.ab_test,
a.pid,
a.user_id,
a.article_id,
a.channel_id,
a.log_time,
a.featuremap
from bi_log.feature_log_extract a
left join (select article_id,article_hash_id from stg.db_smzdm_article_article_index where dt='2020-09-27') b on a.article_id=b.article_id and a.channel_id in(11,6,8,31,66)
where a.dt='2020-09-20' and a.featuremap is not null) a) a
where r=1) a
lateral view json_tuple(a.featuremap,'adcode','age_bin','age1_p','age2_p','age3_p','age4_p','age5_p','area','article_image_count','article_tag','article_type','article_word_count','author_attr','b_cnt_article_1d','b_cnt_article_30d','b_cnt_article_7d','b_mean_ctr_1d','b_mean_ctr_30d','b_mean_ctr_7d','b_mean_sec_1d','b_mean_sec_30d','b_mean_sec_7d','baike_com','baike_gmv','baike_orders','baikeid','baoliao','baoliao_source_type','baoliao_userid',
'brandid','buzhi','cate_decision_cost','cate_people_group','cate_repurchase_period','cate_season','cate_sex','cate_warranty_period','cate1_ordertime_creation_date','cate2_ordertime_creation_date','cate3_ordertime_creation_date','cate4_ordertime_creation_date','category_top_n','channel_pref','channelid','chaojiyouxuan','city','click_home','click_home_per_min','com','comment','country','coupon','ctr_home','ctr_lat','ctr_lng','dashang_people_count','device_typeid','district','event','faxian_caiyong_status','gc_type','geohashid','gmv','history_jingxuan_count','history_pub_count','imp_home','imp_home_per_min','impression_regist_time','impressions_interval','insert_card_count','is_30day_min_price','is_30day_min_price_exist_list','is_baopin','is_category_top_n_exist_list','is_jiajing','is_series','jifen','jinbi','jingyan','level','level1','level2','level3','level4','link_click_ratio','lk','lt_30day_avg_price_ratio','lt_30day_avg_price_ratio_exist_list','lt_last_price_ratio','lt_last_price_ratio_exist_list','mall_pref','mallid','orders','percent_reduction','pinglun','poi_typeid','pre_sale_start_time_creation_date','price','price_diff','price_last','product_ordertime_creation_date','province','pv_every_min','qiandao','reduce_price_type1','reduce_price_type2','reduce_price_type3','reduce_price_type4','reduce_price_type5','reduce_price_type6','reduce_price_type7','reduce_price_type8','score_article','score_quality','sec_click_every_min','sex_p','sexPREFratio_1','sexPREFratio_2','sexPREFratio_3','shoucang','single','subtitle_len','sv','title_len','title_population_type','title_sex','u_brand_ctr_1d','u_brand_ctr_30d','u_brand_ctr_7d','u_brand_sec_1d','u_brand_sec_30d','u_brand_sec_7d','u_cate_sex_1','u_cate_sex_2','u_cate_sex_3','u_ctr_1d','u_ctr_30d','u_ctr_7d','u_sec_1d','u_sec_30d','u_sec_7d','ugz_author_time_diff','ugz_brand_time_diff','ugz_cate1_time_diff','ugz_cate2_time_diff','ugz_cate3_time_diff','ugz_cate4_time_diff','ugz_mall_time_diff','ugz_product_time_diff','ui_is_cargo','up_brand','up_level1','up_level2','up_level3','up_level4','up_tag_avg','up_tag_count','up_tag_max','up_tag_sum','urhoclick_brand_5m','urhoclick_cate1_5m','urhoclick_cate2_5m','urhoclick_cate3_5m','urhoclick_cate4_5m','urhoctr_brand_5m','urhoctr_cate1_5m','urhoctr_cate2_5m','urhoctr_cate3_5m','urhoctr_cate4_5m','urhoimp_brand_5m','urhoimp_cate1_5m','urhoimp_cate2_5m','urhoimp_cate3_5m','urhoimp_cate4_5m','url_com','url_gmv','url_orders','user_com','user_gmv','user_orders','week_day','yh_type','yuanchuang','zhi','zhi_buzhi','zhi_jia_buzhi','zhi_percent_pinglun','zip',
'age','province_code','sex','zhimafen','l1_atcgrd','l1_pp_delta','l1_upp','l2_atcgrd','l2_pp_delta','l2_upp','l3_atcgrd','l3_pp_delta','l3_upp','l4_atcgrd','l4_pp_delta','l4_upp','urhoimp_cate1_24h','urhoimp_cate2_24h','urhoimp_cate3_24h','urhoimp_cate4_24h','urhoclick_cate1_24h','urhoclick_cate2_24h','urhoclick_cate3_24h','urhoclick_cate4_24h','urhoctr_cate1_24h','urhoctr_cate2_24h','urhoctr_cate3_24h','urhoctr_cate4_24h','urhoimp_brand_24h','urhoclick_brand_24h','urhoctr_brand_24h','urhoimp_cate1_15m','urhoimp_cate2_15m','urhoimp_cate3_15m','urhoimp_cate4_15m','urhoclick_cate1_15m','urhoclick_cate2_15m','urhoclick_cate3_15m','urhoclick_cate4_15m','urhoctr_cate1_15m','urhoctr_cate2_15m','urhoctr_cate3_15m','urhoctr_cate4_15m','urhoimp_brand_15m','urhoclick_brand_15m','urhoctr_brand_15m','urhoimp_cate1_150s','urhoimp_cate2_150s','urhoimp_cate3_150s','urhoimp_cate4_150s','urhoclick_cate1_150s','urhoclick_cate2_150s','urhoclick_cate3_150s','urhoclick_cate4_150s','urhoctr_cate1_150s','urhoctr_cate2_150s','urhoctr_cate3_150s','urhoctr_cate4_150s','urhoimp_brand_150s','urhoclick_brand_150s','urhoctr_brand_150s','urseclick_cate1_15m','urseclick_cate2_15m','urseclick_cate3_15m','urseclick_cate4_15m','urseclick_brand_15m','urseclick_cate1_24h','urseclick_cate2_24h','urseclick_cate3_24h','urseclick_cate4_24h','urseclick_brand_24h','ulastclick_cate1','ulastclick_cate2','ulastclick_cate3','ulastclick_cate4','mall_last_1h_ec','mall_last_1h_ec_trend','mall_last_1h_imp','mall_last_1h_imp_trend',
'mall_last_1h_ec_per_imp','mall_last_1h_ec_per_imp_trend','mall_cate_last_1h_ec','mall_cate_last_1h_ec_trend','mall_cate_last_1h_imp','mall_cate_last_1h_imp_trend','mall_cate_last_1h_ec_per_imp','mall_cate_last_1h_ec_per_imp_trend',
'u_last_clk_cate1','u_last_clk_cate1_is_same','u_last_clk_cate2','u_last_clk_cate2_is_same','u_last_clk_cate3','u_last_clk_cate3_is_same','u_last_clk_cate4','u_last_clk_cate4_is_same','u_last_clk_brand','u_last_clk_brand_is_same','u_last_clk_mall','u_last_clk_mall_is_same','u_last_clk_cate1_delta','u_last_clk_cate2_delta','u_last_clk_cate3_delta','u_last_clk_cate4_delta','u_last_clk_brand_delta','u_last_clk_mall_delta','single_imp_ec','avg_time','avg_finish',
'mu_o_1d','mu_o_7d','mu_o_30d','mu_g_1d','mu_g_7d','mu_g_30d','mu_sec_1d','mu_sec_7d','mu_sec_30d','mu_op_1d','mu_op_7d','mu_op_30d','mu_o_3h_rt','mu_g_3h_rt','mu_sec_3h_rt','mu_op_3h_rt','uo_l1_1d_o','uo_l1_7d_o','uo_l1_30d_o','uo_l1_1d_g','uo_l1_7d_g','uo_l1_30d_g','uo_l2_1d_o','uo_l2_7d_o','uo_l2_30d_o','uo_l2_1d_g','uo_l2_7d_g','uo_l2_30d_g','uo_l3_1d_o','uo_l3_7d_o','uo_l3_30d_o','uo_l3_1d_g','uo_l3_7d_g','uo_l3_30d_g','uo_l4_1d_o','uo_l4_7d_o','uo_l4_30d_o',
'uo_l4_1d_g','uo_l4_7d_g','uo_l4_30d_g','uo_l1_1d_sec','uo_l1_7d_sec','uo_l1_30d_sec','uo_l2_1d_sec','uo_l2_7d_sec','uo_l2_30d_sec','uo_l3_1d_sec','uo_l3_7d_sec','uo_l3_30d_sec','uo_l4_1d_sec','uo_l4_7d_sec','uo_l4_30d_sec','uo_l1_1d_op','uo_l1_7d_op','uo_l1_30d_op','uo_l2_1d_op','uo_l2_7d_op','uo_l2_30d_op','uo_l3_1d_op','uo_l3_7d_op','uo_l3_30d_op','uo_l4_1d_op','uo_l4_7d_op','uo_l4_30d_op','uo_l1_3h_g_rt','uo_l1_3h_o_rt','uo_l2_3h_g_rt','uo_l2_3h_o_rt',
'uo_l3_3h_g_rt','uo_l3_3h_o_rt','uo_l4_3h_g_rt','uo_l4_3h_o_rt','uo_l1_3h_sec_rt','uo_l2_3h_sec_rt','uo_l3_3h_sec_rt','uo_l4_3h_sec_rt','uo_l1_3h_op_rt','uo_l2_3h_op_rt','uo_l3_3h_op_rt','uo_l4_3h_op_rt',
'os_version',
'screen_height',
'screen_width',
'app_market',
'net_type',
'mu_o_12h_rt',
'mu_sec_12h_rt',
'mu_op_12h_rt',
'uo_l1_90d_o',
'uo_l1_180d_o',
'uo_l2_90d_o',
'uo_l2_180d_o',
'uo_l3_90d_o',
'uo_l3_180d_o',
'uo_l4_90d_o',
'uo_l4_180d_o',
'uo_l1_90d_sec',
'uo_l1_180d_sec',
'uo_l2_90d_sec',
'uo_l2_180d_sec',
'uo_l3_90d_sec',
'uo_l3_180d_sec',
'uo_l4_90d_sec',
'uo_l4_180d_sec',
'uo_l1_90d_op',
'uo_l1_180d_op',
'uo_l2_90d_op',
'uo_l2_180d_op',
'uo_l3_90d_op',
'uo_l3_180d_op',
'uo_l4_90d_op',
'uo_l4_180d_op',
'anticheat_by_zhi',
'anticheat_by_comment',
'anticheat_by_shoucang',
'up_level1_ct_3d',
'up_level1_ct_7d',
'up_level1_ct_30d',
'up_level1_ct_90d',
'up_level1_ct_180d',
'up_level2_ct_3d',
'up_level2_ct_7d',
'up_level2_ct_30d',
'up_level2_ct_90d',
'up_level2_ct_180d',
'up_level3_ct_3d',
'up_level3_ct_7d',
'up_level3_ct_30d',
'up_level3_ct_90d',
'up_level3_ct_180d',
'up_level4_ct_3d',
'up_level4_ct_7d',
'up_level4_ct_30d',
'up_level4_ct_90d',
'up_level4_ct_180d',
'up_level1_sec_3d',
'up_level1_sec_7d',
'up_level1_sec_30d',
'up_level1_sec_90d',
'up_level1_sec_180d',
'up_level2_sec_3d',
'up_level2_sec_7d',
'up_level2_sec_30d',
'up_level2_sec_90d',
'up_level2_sec_180d',
'up_level3_sec_3d',
'up_level3_sec_7d',
'up_level3_sec_30d',
'up_level3_sec_90d',
'up_level3_sec_180d',
'up_level4_sec_3d',
'up_level4_sec_7d',
'up_level4_sec_30d',
'up_level4_sec_90d',
'up_level4_sec_180d',
'ua_clst_3h_ctr',
'ua_clst_3h_sec',
'u_clst_id',
'is_jingdou'
) b
as adcode,age_bin,age1_p,age2_p,age3_p,age4_p,age5_p,area,article_image_count,article_tag,article_type,article_word_count,author_attr,b_cnt_article_1d,b_cnt_article_30d,b_cnt_article_7d,b_mean_ctr_1d,b_mean_ctr_30d,b_mean_ctr_7d,b_mean_sec_1d,b_mean_sec_30d,b_mean_sec_7d,baike_com,baike_gmv,baike_orders,baikeid,baoliao,baoliao_source_type,baoliao_userid,brandid,buzhi,cate_decision_cost,cate_people_group,cate_repurchase_period,cate_season,cate_sex,cate_warranty_period,cate1_ordertime_creation_date,cate2_ordertime_creation_date,cate3_ordertime_creation_date,cate4_ordertime_creation_date,category_top_n,channel_pref,channelid,chaojiyouxuan,city,click_home,click_home_per_min,com,comment,country,coupon,ctr_home,ctr_lat,ctr_lng,dashang_people_count,device_typeid,district,event,faxian_caiyong_status,gc_type,geohashid,gmv,history_jingxuan_count,history_pub_count,imp_home,imp_home_per_min,impression_regist_time,impressions_interval,insert_card_count,is_30day_min_price,is_30day_min_price_exist_list,is_baopin,is_category_top_n_exist_list,is_jiajing,is_series,jifen,jinbi,jingyan,level,level1,level2,level3,level4,link_click_ratio,lk,lt_30day_avg_price_ratio,lt_30day_avg_price_ratio_exist_list,lt_last_price_ratio,lt_last_price_ratio_exist_list,mall_pref,mallid,orders,percent_reduction,pinglun,poi_typeid,pre_sale_start_time_creation_date,price,price_diff,price_last,product_ordertime_creation_date,province,pv_every_min,qiandao,reduce_price_type1,reduce_price_type2,reduce_price_type3,reduce_price_type4,reduce_price_type5,reduce_price_type6,reduce_price_type7,reduce_price_type8,score_article,score_quality,sec_click_every_min,sex_p,sexPREFratio_1,sexPREFratio_2,sexPREFratio_3,shoucang,single,subtitle_len,sv,title_len,title_population_type,title_sex,u_brand_ctr_1d,u_brand_ctr_30d,u_brand_ctr_7d,u_brand_sec_1d,u_brand_sec_30d,u_brand_sec_7d,u_cate_sex_1,u_cate_sex_2,u_cate_sex_3,u_ctr_1d,u_ctr_30d,u_ctr_7d,u_sec_1d,u_sec_30d,u_sec_7d,ugz_author_time_diff,ugz_brand_time_diff,ugz_cate1_time_diff,ugz_cate2_time_diff,ugz_cate3_time_diff,ugz_cate4_time_diff,ugz_mall_time_diff,ugz_product_time_diff,ui_is_cargo,up_brand,up_level1,up_level2,up_level3,up_level4,up_tag_avg,up_tag_count,up_tag_max,up_tag_sum,urhoclick_brand_5m,urhoclick_cate1_5m,urhoclick_cate2_5m,urhoclick_cate3_5m,urhoclick_cate4_5m,urhoctr_brand_5m,urhoctr_cate1_5m,urhoctr_cate2_5m,urhoctr_cate3_5m,urhoctr_cate4_5m,urhoimp_brand_5m,urhoimp_cate1_5m,urhoimp_cate2_5m,urhoimp_cate3_5m,urhoimp_cate4_5m,url_com,url_gmv,url_orders,user_com,user_gmv,user_orders,week_day,yh_type,yuanchuang,zhi,zhi_buzhi,zhi_jia_buzhi,zhi_percent_pinglun,zip,age,province_code,sex,zhimafen,l1_atcgrd,l1_pp_delta,l1_upp,l2_atcgrd,l2_pp_delta,l2_upp,l3_atcgrd,l3_pp_delta,l3_upp,l4_atcgrd,l4_pp_delta,l4_upp,urhoimp_cate1_24h,urhoimp_cate2_24h,urhoimp_cate3_24h,urhoimp_cate4_24h,urhoclick_cate1_24h,urhoclick_cate2_24h,urhoclick_cate3_24h,urhoclick_cate4_24h,urhoctr_cate1_24h,urhoctr_cate2_24h,urhoctr_cate3_24h,urhoctr_cate4_24h,urhoimp_brand_24h,urhoclick_brand_24h,urhoctr_brand_24h,urhoimp_cate1_15m,urhoimp_cate2_15m,urhoimp_cate3_15m,urhoimp_cate4_15m,urhoclick_cate1_15m,urhoclick_cate2_15m,urhoclick_cate3_15m,urhoclick_cate4_15m,urhoctr_cate1_15m,urhoctr_cate2_15m,urhoctr_cate3_15m,urhoctr_cate4_15m,urhoimp_brand_15m,urhoclick_brand_15m,urhoctr_brand_15m,urhoimp_cate1_150s,urhoimp_cate2_150s,urhoimp_cate3_150s,urhoimp_cate4_150s,urhoclick_cate1_150s,urhoclick_cate2_150s,urhoclick_cate3_150s,urhoclick_cate4_150s,urhoctr_cate1_150s,urhoctr_cate2_150s,urhoctr_cate3_150s,urhoctr_cate4_150s,urhoimp_brand_150s,urhoclick_brand_150s,urhoctr_brand_150s,urseclick_cate1_15m,urseclick_cate2_15m,urseclick_cate3_15m,urseclick_cate4_15m,urseclick_brand_15m,urseclick_cate1_24h,urseclick_cate2_24h,urseclick_cate3_24h,urseclick_cate4_24h,urseclick_brand_24h,ulastclick_cate1,ulastclick_cate2,ulastclick_cate3,ulastclick_cate4,mall_last_1h_ec,mall_last_1h_ec_trend,mall_last_1h_imp,mall_last_1h_imp_trend,mall_last_1h_ec_per_imp,mall_last_1h_ec_per_imp_trend,mall_cate_last_1h_ec,mall_cate_last_1h_ec_trend,mall_cate_last_1h_imp,mall_cate_last_1h_imp_trend,mall_cate_last_1h_ec_per_imp,mall_cate_last_1h_ec_per_imp_trend,u_last_clk_cate1,u_last_clk_cate1_is_same,u_last_clk_cate2,u_last_clk_cate2_is_same,u_last_clk_cate3,u_last_clk_cate3_is_same,u_last_clk_cate4,u_last_clk_cate4_is_same,u_last_clk_brand,u_last_clk_brand_is_same,u_last_clk_mall,u_last_clk_mall_is_same,u_last_clk_cate1_delta,u_last_clk_cate2_delta,u_last_clk_cate3_delta,u_last_clk_cate4_delta,u_last_clk_brand_delta,u_last_clk_mall_delta,single_imp_ec,avg_time,avg_finish,mu_o_1d,mu_o_7d,mu_o_30d,mu_g_1d,mu_g_7d,mu_g_30d,mu_sec_1d,mu_sec_7d,mu_sec_30d,mu_op_1d,mu_op_7d,mu_op_30d,mu_o_3h_rt,mu_g_3h_rt,mu_sec_3h_rt,mu_op_3h_rt,uo_l1_1d_o,uo_l1_7d_o,uo_l1_30d_o,uo_l1_1d_g,uo_l1_7d_g,uo_l1_30d_g,uo_l2_1d_o,uo_l2_7d_o,uo_l2_30d_o,uo_l2_1d_g,uo_l2_7d_g,uo_l2_30d_g,uo_l3_1d_o,uo_l3_7d_o,uo_l3_30d_o,uo_l3_1d_g,uo_l3_7d_g,uo_l3_30d_g,uo_l4_1d_o,uo_l4_7d_o,uo_l4_30d_o,uo_l4_1d_g,uo_l4_7d_g,uo_l4_30d_g,uo_l1_1d_sec,uo_l1_7d_sec,uo_l1_30d_sec,uo_l2_1d_sec,uo_l2_7d_sec,uo_l2_30d_sec,uo_l3_1d_sec,uo_l3_7d_sec,uo_l3_30d_sec,uo_l4_1d_sec,uo_l4_7d_sec,uo_l4_30d_sec,uo_l1_1d_op,uo_l1_7d_op,uo_l1_30d_op,uo_l2_1d_op,uo_l2_7d_op,uo_l2_30d_op,uo_l3_1d_op,uo_l3_7d_op,uo_l3_30d_op,uo_l4_1d_op,uo_l4_7d_op,uo_l4_30d_op,uo_l1_3h_g_rt,uo_l1_3h_o_rt,uo_l2_3h_g_rt,uo_l2_3h_o_rt,uo_l3_3h_g_rt,uo_l3_3h_o_rt,uo_l4_3h_g_rt,uo_l4_3h_o_rt,uo_l1_3h_sec_rt,uo_l2_3h_sec_rt,uo_l3_3h_sec_rt,uo_l4_3h_sec_rt,uo_l1_3h_op_rt,uo_l2_3h_op_rt,uo_l3_3h_op_rt,uo_l4_3h_op_rt,
os_version,
screen_height,
screen_width,
app_market,
net_type,
mu_o_12h_rt,
mu_sec_12h_rt,
mu_op_12h_rt,
uo_l1_90d_o,
uo_l1_180d_o,
uo_l2_90d_o,
uo_l2_180d_o,
uo_l3_90d_o,
uo_l3_180d_o,
uo_l4_90d_o,
uo_l4_180d_o,
uo_l1_90d_sec,
uo_l1_180d_sec,
uo_l2_90d_sec,
uo_l2_180d_sec,
uo_l3_90d_sec,
uo_l3_180d_sec,
uo_l4_90d_sec,
uo_l4_180d_sec,
uo_l1_90d_op,
uo_l1_180d_op,
uo_l2_90d_op,
uo_l2_180d_op,
uo_l3_90d_op,
uo_l3_180d_op,
uo_l4_90d_op,
uo_l4_180d_op,
anticheat_by_zhi,
anticheat_by_comment,
anticheat_by_shoucang,
up_level1_ct_3d,
up_level1_ct_7d,
up_level1_ct_30d,
up_level1_ct_90d,
up_level1_ct_180d,
up_level2_ct_3d,
up_level2_ct_7d,
up_level2_ct_30d,
up_level2_ct_90d,
up_level2_ct_180d,
up_level3_ct_3d,
up_level3_ct_7d,
up_level3_ct_30d,
up_level3_ct_90d,
up_level3_ct_180d,
up_level4_ct_3d,
up_level4_ct_7d,
up_level4_ct_30d,
up_level4_ct_90d,
up_level4_ct_180d,
up_level1_sec_3d,
up_level1_sec_7d,
up_level1_sec_30d,
up_level1_sec_90d,
up_level1_sec_180d,
up_level2_sec_3d,
up_level2_sec_7d,
up_level2_sec_30d,
up_level2_sec_90d,
up_level2_sec_180d,
up_level3_sec_3d,
up_level3_sec_7d,
up_level3_sec_30d,
up_level3_sec_90d,
up_level3_sec_180d,
up_level4_sec_3d,
up_level4_sec_7d,
up_level4_sec_30d,
up_level4_sec_90d,
up_level4_sec_180d,
ua_clst_3h_ctr,
ua_clst_3h_sec,
u_clst_id,
is_jingdou;


--12313.727

create table bi_test.zyl_tmp_200928_5 as
select
a.id,
a.creation_date,
a.user_id,
a.device_id,
a.remark,
a.type,
a.remark2,
a.remark3,
a.version,
a.article_id,
a.remark4,
a.is_click,
a.is_event,
a.is_order,
b.adcode,
b.age_bin,
b.age1_p,
b.age2_p,
b.age3_p,
b.age4_p,
b.age5_p,
b.area,
b.article_image_count,
b.article_tag,
b.article_type,
b.article_word_count,
b.author_attr,
b.b_cnt_article_1d,
b.b_cnt_article_30d,
b.b_cnt_article_7d,
b.b_mean_ctr_1d,
b.b_mean_ctr_30d,
b.b_mean_ctr_7d,
b.b_mean_sec_1d,
b.b_mean_sec_30d,
b.b_mean_sec_7d,
b.baike_com,
b.baike_gmv,
b.baike_orders,
b.baikeid,
b.baoliao,
b.baoliao_source_type,
b.baoliao_userid,
b.brandid,
b.buzhi,
b.cate_decision_cost,
b.cate_people_group,
b.cate_repurchase_period,
b.cate_season,
b.cate_sex,
b.cate_warranty_period,
b.cate1_ordertime_creation_date,
b.cate2_ordertime_creation_date,
b.cate3_ordertime_creation_date,
b.cate4_ordertime_creation_date,
b.category_top_n,
b.channel_pref,
b.channelid,
b.chaojiyouxuan,
b.city,
b.click_home,
b.click_home_per_min,
b.com,
b.comment,
b.country,
b.coupon,
b.ctr_home,
b.ctr_lat,
b.ctr_lng,
b.dashang_people_count,
b.device_typeid,
b.district,
b.event,
b.faxian_caiyong_status,
b.gc_type,
b.geohashid,
b.gmv,
b.history_jingxuan_count,
b.history_pub_count,
b.imp_home,
b.imp_home_per_min,
b.impression_regist_time,
b.impressions_interval,
b.insert_card_count,
b.is_30day_min_price,
b.is_30day_min_price_exist_list,
b.is_baopin,
b.is_category_top_n_exist_list,
b.is_jiajing,
b.is_series,
b.jifen,
b.jinbi,
b.jingyan,
b.level,
b.level1,
b.level2,
b.level3,
b.level4,
b.link_click_ratio,
b.lk,
b.lt_30day_avg_price_ratio,
b.lt_30day_avg_price_ratio_exist_list,
b.lt_last_price_ratio,
b.lt_last_price_ratio_exist_list,
b.mall_pref,
b.mallid,
b.orders,
b.percent_reduction,
b.pinglun,
b.poi_typeid,
b.pre_sale_start_time_creation_date,
b.price,
b.price_diff,
b.price_last,
b.product_ordertime_creation_date,
b.province,
b.pv_every_min,
b.qiandao,
b.reduce_price_type1,
b.reduce_price_type2,
b.reduce_price_type3,
b.reduce_price_type4,
b.reduce_price_type5,
b.reduce_price_type6,
b.reduce_price_type7,
b.reduce_price_type8,
b.score_article,
b.score_quality,
b.sec_click_every_min,
b.sex_p,
b.sexPREFratio_1,
b.sexPREFratio_2,
b.sexPREFratio_3,
b.shoucang,
b.single,
b.subtitle_len,
b.sv,
b.title_len,
b.title_population_type,
b.title_sex,
b.u_brand_ctr_1d,
b.u_brand_ctr_30d,
b.u_brand_ctr_7d,
b.u_brand_sec_1d,
b.u_brand_sec_30d,
b.u_brand_sec_7d,
b.u_cate_sex_1,
b.u_cate_sex_2,
b.u_cate_sex_3,
b.u_ctr_1d,
b.u_ctr_30d,
b.u_ctr_7d,
b.u_sec_1d,
b.u_sec_30d,
b.u_sec_7d,
b.ugz_author_time_diff,
b.ugz_brand_time_diff,
b.ugz_cate1_time_diff,
b.ugz_cate2_time_diff,
b.ugz_cate3_time_diff,
b.ugz_cate4_time_diff,
b.ugz_mall_time_diff,
b.ugz_product_time_diff,
b.ui_is_cargo,
b.up_brand,
b.up_level1,
b.up_level2,
b.up_level3,
b.up_level4,
b.up_tag_avg,
b.up_tag_count,
b.up_tag_max,
b.up_tag_sum,
b.urhoclick_brand_5m,
b.urhoclick_cate1_5m,
b.urhoclick_cate2_5m,
b.urhoclick_cate3_5m,
b.urhoclick_cate4_5m,
b.urhoctr_brand_5m,
b.urhoctr_cate1_5m,
b.urhoctr_cate2_5m,
b.urhoctr_cate3_5m,
b.urhoctr_cate4_5m,
b.urhoimp_brand_5m,
b.urhoimp_cate1_5m,
b.urhoimp_cate2_5m,
b.urhoimp_cate3_5m,
b.urhoimp_cate4_5m,
b.url_com,
b.url_gmv,
b.url_orders,
b.user_com,
b.user_gmv,
b.user_orders,
b.week_day,
b.yh_type,
b.yuanchuang,
b.zhi,
b.zhi_buzhi,
b.zhi_jia_buzhi,
b.zhi_percent_pinglun,
b.zip,
b.age,
b.province_code,
b.sex,
b.zhimafen,
b.l1_atcgrd,
b.l1_pp_delta,
b.l1_upp,
b.l2_atcgrd,
b.l2_pp_delta,
b.l2_upp,
b.l3_atcgrd,
b.l3_pp_delta,
b.l3_upp,
b.l4_atcgrd,
b.l4_pp_delta,
b.l4_upp,
b.urhoimp_cate1_24h,
b.urhoimp_cate2_24h,
b.urhoimp_cate3_24h,
b.urhoimp_cate4_24h,
b.urhoclick_cate1_24h,
b.urhoclick_cate2_24h,
b.urhoclick_cate3_24h,
b.urhoclick_cate4_24h,
b.urhoctr_cate1_24h,
b.urhoctr_cate2_24h,
b.urhoctr_cate3_24h,
b.urhoctr_cate4_24h,
b.urhoimp_brand_24h,
b.urhoclick_brand_24h,
b.urhoctr_brand_24h,
b.urhoimp_cate1_15m,
b.urhoimp_cate2_15m,
b.urhoimp_cate3_15m,
b.urhoimp_cate4_15m,
b.urhoclick_cate1_15m,
b.urhoclick_cate2_15m,
b.urhoclick_cate3_15m,
b.urhoclick_cate4_15m,
b.urhoctr_cate1_15m,
b.urhoctr_cate2_15m,
b.urhoctr_cate3_15m,
b.urhoctr_cate4_15m,
b.urhoimp_brand_15m,
b.urhoclick_brand_15m,
b.urhoctr_brand_15m,
b.urhoimp_cate1_150s,
b.urhoimp_cate2_150s,
b.urhoimp_cate3_150s,
b.urhoimp_cate4_150s,
b.urhoclick_cate1_150s,
b.urhoclick_cate2_150s,
b.urhoclick_cate3_150s,
b.urhoclick_cate4_150s,
b.urhoctr_cate1_150s,
b.urhoctr_cate2_150s,
b.urhoctr_cate3_150s,
b.urhoctr_cate4_150s,
b.urhoimp_brand_150s,
b.urhoclick_brand_150s,
b.urhoctr_brand_150s,
b.urseclick_cate1_15m,
b.urseclick_cate2_15m,
b.urseclick_cate3_15m,
b.urseclick_cate4_15m,
b.urseclick_brand_15m,
b.urseclick_cate1_24h,
b.urseclick_cate2_24h,
b.urseclick_cate3_24h,
b.urseclick_cate4_24h,
b.urseclick_brand_24h,
b.ulastclick_cate1,
b.ulastclick_cate2,
b.ulastclick_cate3,
b.ulastclick_cate4,
b.mall_last_1h_ec,
b.mall_last_1h_ec_trend,
b.mall_last_1h_imp,
b.mall_last_1h_imp_trend,
b.mall_last_1h_ec_per_imp,
b.mall_last_1h_ec_per_imp_trend,
b.mall_cate_last_1h_ec,
b.mall_cate_last_1h_ec_trend,
b.mall_cate_last_1h_imp,
b.mall_cate_last_1h_imp_trend,
b.mall_cate_last_1h_ec_per_imp,
b.mall_cate_last_1h_ec_per_imp_trend,
b.u_last_clk_cate1,
b.u_last_clk_cate1_is_same,
b.u_last_clk_cate2,
b.u_last_clk_cate2_is_same,
b.u_last_clk_cate3,
b.u_last_clk_cate3_is_same,
b.u_last_clk_cate4,
b.u_last_clk_cate4_is_same,
b.u_last_clk_brand,
b.u_last_clk_brand_is_same,
b.u_last_clk_mall,
b.u_last_clk_mall_is_same,
b.u_last_clk_cate1_delta,
b.u_last_clk_cate2_delta,
b.u_last_clk_cate3_delta,
b.u_last_clk_cate4_delta,
b.u_last_clk_brand_delta,
b.u_last_clk_mall_delta,
b.single_imp_ec,
b.avg_time,
b.avg_finish,
b.mu_o_1d,
b.mu_o_7d,
b.mu_o_30d,
b.mu_g_1d,
b.mu_g_7d,
b.mu_g_30d,
b.mu_sec_1d,
b.mu_sec_7d,
b.mu_sec_30d,
b.mu_op_1d,
b.mu_op_7d,
b.mu_op_30d,
b.mu_o_3h_rt,
b.mu_g_3h_rt,
b.mu_sec_3h_rt,
b.mu_op_3h_rt,
b.uo_l1_1d_o,
b.uo_l1_7d_o,
b.uo_l1_30d_o,
b.uo_l1_1d_g,
b.uo_l1_7d_g,
b.uo_l1_30d_g,
b.uo_l2_1d_o,
b.uo_l2_7d_o,
b.uo_l2_30d_o,
b.uo_l2_1d_g,
b.uo_l2_7d_g,
b.uo_l2_30d_g,
b.uo_l3_1d_o,
b.uo_l3_7d_o,
b.uo_l3_30d_o,
b.uo_l3_1d_g,
b.uo_l3_7d_g,
b.uo_l3_30d_g,
b.uo_l4_1d_o,
b.uo_l4_7d_o,
b.uo_l4_30d_o,
b.uo_l4_1d_g,
b.uo_l4_7d_g,
b.uo_l4_30d_g,
b.uo_l1_1d_sec,
b.uo_l1_7d_sec,
b.uo_l1_30d_sec,
b.uo_l2_1d_sec,
b.uo_l2_7d_sec,
b.uo_l2_30d_sec,
b.uo_l3_1d_sec,
b.uo_l3_7d_sec,
b.uo_l3_30d_sec,
b.uo_l4_1d_sec,
b.uo_l4_7d_sec,
b.uo_l4_30d_sec,
b.uo_l1_1d_op,
b.uo_l1_7d_op,
b.uo_l1_30d_op,
b.uo_l2_1d_op,
b.uo_l2_7d_op,
b.uo_l2_30d_op,
b.uo_l3_1d_op,
b.uo_l3_7d_op,
b.uo_l3_30d_op,
b.uo_l4_1d_op,
b.uo_l4_7d_op,
b.uo_l4_30d_op,
b.uo_l1_3h_g_rt,
b.uo_l1_3h_o_rt,
b.uo_l2_3h_g_rt,
b.uo_l2_3h_o_rt,
b.uo_l3_3h_g_rt,
b.uo_l3_3h_o_rt,
b.uo_l4_3h_g_rt,
b.uo_l4_3h_o_rt,
b.uo_l1_3h_sec_rt,
b.uo_l2_3h_sec_rt,
b.uo_l3_3h_sec_rt,
b.uo_l4_3h_sec_rt,
b.uo_l1_3h_op_rt,
b.uo_l2_3h_op_rt,
b.uo_l3_3h_op_rt,
b.uo_l4_3h_op_rt,
b.os_version,
b.screen_height,
b.screen_width,
b.app_market,
b.net_type,
b.mu_o_12h_rt,
b.mu_sec_12h_rt,
b.mu_op_12h_rt,
b.uo_l1_90d_o,
b.uo_l1_180d_o,
b.uo_l2_90d_o,
b.uo_l2_180d_o,
b.uo_l3_90d_o,
b.uo_l3_180d_o,
b.uo_l4_90d_o,
b.uo_l4_180d_o,
b.uo_l1_90d_sec,
b.uo_l1_180d_sec,
b.uo_l2_90d_sec,
b.uo_l2_180d_sec,
b.uo_l3_90d_sec,
b.uo_l3_180d_sec,
b.uo_l4_90d_sec,
b.uo_l4_180d_sec,
b.uo_l1_90d_op,
b.uo_l1_180d_op,
b.uo_l2_90d_op,
b.uo_l2_180d_op,
b.uo_l3_90d_op,
b.uo_l3_180d_op,
b.uo_l4_90d_op,
b.uo_l4_180d_op,
b.anticheat_by_zhi,
b.anticheat_by_comment,
b.anticheat_by_shoucang,
b.up_level1_ct_3d,
b.up_level1_ct_7d,
b.up_level1_ct_30d,
b.up_level1_ct_90d,
b.up_level1_ct_180d,
b.up_level2_ct_3d,
b.up_level2_ct_7d,
b.up_level2_ct_30d,
b.up_level2_ct_90d,
b.up_level2_ct_180d,
b.up_level3_ct_3d,
b.up_level3_ct_7d,
b.up_level3_ct_30d,
b.up_level3_ct_90d,
b.up_level3_ct_180d,
b.up_level4_ct_3d,
b.up_level4_ct_7d,
b.up_level4_ct_30d,
b.up_level4_ct_90d,
b.up_level4_ct_180d,
b.up_level1_sec_3d,
b.up_level1_sec_7d,
b.up_level1_sec_30d,
b.up_level1_sec_90d,
b.up_level1_sec_180d,
b.up_level2_sec_3d,
b.up_level2_sec_7d,
b.up_level2_sec_30d,
b.up_level2_sec_90d,
b.up_level2_sec_180d,
b.up_level3_sec_3d,
b.up_level3_sec_7d,
b.up_level3_sec_30d,
b.up_level3_sec_90d,
b.up_level3_sec_180d,
b.up_level4_sec_3d,
b.up_level4_sec_7d,
b.up_level4_sec_30d,
b.up_level4_sec_90d,
b.up_level4_sec_180d,
b.ua_clst_3h_ctr,
b.ua_clst_3h_sec,
b.u_clst_id,
b.is_jingdou,
'2020-09-20' dt
from bi_test.zyl_tmp_200928_2 a
left join bi_test.zyl_tmp_200928_4 b on a.id=b.id;
